version: "3.7"

services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DB: todofrog
      POSTGRES_USER: todofrog
      POSTGRES_PASSWORD: todofrog
    ports:
      - 5435:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
